name: ✨ 教程建议
description: 建议一个新的教程或者对现有教程提出改进意见。
title: "[建议]: "
body:
- type: checkboxes
  id: check-answer
  attributes:
    label: 检查列表
    description: 在提交建议之前，请确保您已完成以下操作。
    options:
      - label: 我已经搜索过现有的 issue 和教程列表，确认没有重复的内容。
        required: true
- type: textarea
  id: problem-description
  attributes:
    label: 您建议添加或改进什么教程？
    description: 请清晰简洁地描述您建议的主题。
  validations:
    required: true
- type: textarea
  id: proposed-solution
  attributes:
    label: 请描述您建议的教程内容
    description: 请提供您建议的教程大纲或关键点。
  validations:
    required: true
- type: textarea
  id: additional-information
  attributes:
    label: 附加信息
    description: 如果你的问题需要进一步解释，或者想要表达其他内容，请在此处添加更多信息。（直接把图片、视频拖到编辑框即可添加图片或视频）
