name: 🐞 报告问题
description: 报告教程中遇到的问题或错误。
title: "[问题]: "
body:
- type: checkboxes
  id: check-answer
  attributes:
    label: 检查列表
    description: 在提交问题之前，请确保您已完成以下操作。
    options:
      - label: 我已经搜索过现有的 issue，确认没有重复的问题。
        required: true
- type: input
  id: tutorial-title
  attributes:
    label: 相关的教程标题
    description: 哪个教程出现了问题？
    placeholder: "例如：安卓调试工具基础教程"
  validations:
    required: true
- type: input
  id: operating-system-version
  attributes:
    label: 操作系统
    description: 您使用的是什么操作系统？（如果相关）
    placeholder: "例如 Ubuntu 20.04, Windows 10"
  validations:
    required: false
- type: textarea
  id: issue-description
  attributes:
    label: 问题描述
    description: 请清晰、简洁地描述您遇到的问题。
  validations:
    required: true
- type: textarea
  id: additional-information
  attributes:
    label: 附加信息
    description: 如果你的问题需要进一步解释，或者想要表达其他内容，请在此处添加更多信息。（直接把图片、视频拖到编辑框即可添加图片或视频）
